# Generated by Django 5.2.1 on 2025-07-08 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_alter_race_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantasyteam',
            name='points',
        ),
        migrations.RemoveField(
            model_name='raceresult',
            name='fastest_lap',
        ),
        migrations.AddField(
            model_name='raceresult',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='constructor',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fantasyteam',
            name='driver_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_driver1', to='fantasy.driver'),
        ),
        migrations.AlterField(
            model_name='fantasyteam',
            name='driver_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_driver2', to='fantasy.driver'),
        ),
        migrations.AlterField(
            model_name='fantasyteam',
            name='total_cost',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='TeamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
