# Generated by Django 5.2.1 on 2025-07-08 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0004_constructor_points_driver_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='constructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.constructor'),
        ),
    ]
