# Generated by Django 5.2.1 on 2025-07-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0007_seasonscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyteam',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
